/* tslint:disable */
/* eslint-disable */
/**
 * Rails API / ReactJS - Template API
 * This is a template about Rails API / ReactJS - Template API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tony.duong.102@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

